### ISSUE TITLE
Cambio en models

### ISSUE THREAD

**Issue by Devnull213** [pag0dy/proyecto_grupal#2]
Muchachos. trabajando en los formularios encontré un potencial problema en el modelo de agrupación. 
El campo categoría:
`categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='agrupacion_relacionada')`
Lo habíamos planeado como un select. Pero no podemos pasarle ningún valor que no sea una instancia de Categoría a este ForeignKey. 
Por lo que la solución que propongo es eliminar la tabla Categoría, que solo contiene nombre y descripción, dejando el campo categoría perteneciente a agrupación como un CharField que reciba las opciones del select. De todas maneras podremos seguir filtrando las agrupaciones por categorias, pero por medio de filter y no por busqueda inversa.

**Comment by aandrewsv** [comment]
Estoy de acuerdo con la solución. Sólo habrá que prescindir de la descripción de las categorías, pero no creo que sea fundamental esa parte.

**Comment by pag0dy** [comment]
Me parece que es una super buena propuesta Michel, estoy de acuerdo!
