### ISSUE TITLE
View de proceso registro para Agrupaciones

### ISSUE THREAD

**Issue by pag0dy** [pag0dy/proyecto_grupal#27]
Nos falta una view que haga el registro para las agrupaciones (sólo reciba POST y redireccione). @maritaschmutzer lo ves tú?

**Comment by maritaschmutzer** [comment]
si! estaba dandole una vuelta a como hacerlo, debería ser con entrada oculta o no? dado que se visualizará en la misma view que el registro de usuario

**Comment by pag0dy** [comment]
no necesariamente, como son dos forms a parte, mandan el post a distintas direcciones... si haces un pull de lo que hay ahora, vas a ver que yo cree un view que se llama registro_agrupacion. Ahí es donde iría el post del form de registro para agrupaciones, así que ahí se tiene que procesar la información y luego redireccionar.

**Comment by maritaschmutzer** [comment]
perfect, ya está funcionando me parece!
